# Generated by Django 6.0.3 on 2026-03-07 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0004_alter_genre_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="order",
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="movie_session",
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={},
        ),
        migrations.AlterModelOptions(
            name="moviesession",
            options={},
        ),
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(related_name="movies", to="cinema.actor"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(related_name="movies", to="cinema.genre"),
        ),
        migrations.AlterField(
            model_name="moviesession",
            name="cinema_hall",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="cinema.cinemahall",
            ),
        ),
        migrations.AlterField(
            model_name="moviesession",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="cinema.movie",
            ),
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Ticket",
        ),
    ]
